name: "My FiveM RP Server - ND Core"
author: "YourName"
version: "1.0"
description: "FiveM Full RP Server using ND Core & OX Resources"

dependencies:
  - "nd_core"
  - "ox_lib"
  - "ox_mysql"
  - "ox_target"
  - "ox_inventory"

tasks:
  - name: "Start Database"
    action: command
    command: "start ox_mysql"

  - name: "Load Core Scripts"
    action: command
    command: |
      start nd_core
      start ox_lib
      start ox_target
      start ox_inventory
      start ox_mysql

  - name: "Load Character & UI System"
    action: command
    command: |
      start nd_characters
      start nd_appearance
      start nd_spawn
      start nd_hud

  - name: "Load Economy & Business"
    action: command
    command: |
      start nd_banking
      start nd_cityhall
      start nd_management

  - name: "Load Job System"
    action: command
    command: |
      start nd_jobs
      start nd_vehicleshop
      start nd_police
      start nd_ambulance
      start nd_gangs
      start nd_mafia

  - name: "Load Crime & Heist System"
    action: command
    command: |
      start nd_drugs
      start nd_prison
      start nd_robbery
      start nd_heists
      start nd_weaponcraft

  - name: "Load Vehicle & Fuel System"
    action: command
    command: |
      start nd_garages
      start nd_fuel

  - name: "Load Miscellaneous Features"
    action: command
    command: |
      start easyadmin
      start nd_logs
      start nd_animations
      start dpemotes

  - name: "Server Ready"
    action: command
    command: "echo Server has been started successfully!"
