name: "Rascal"
author: "abo derascal"
description: "Server Qbox yang stabil dengan fitur fully roleplay dan Illenium Appearance."
version: 1.1

tasks:
  - action: "run"
    command: "git clone --branch main https://github.com/qbox-project/qbox.git resources/[core]/qbox_core"

  - action: "run"
    command: "git clone --branch main https://github.com/overextended/ox_lib.git resources/[core]/ox_lib"

  - action: "run"
    command: "git clone --branch main https://github.com/overextended/ox_target.git resources/[core]/ox_target"

  - action: "run"
    command: "git clone --branch main https://github.com/overextended/ox_inventory.git resources/[core]/ox_inventory"

  - action: "run"
    command: "git clone --branch main https://github.com/overextended/oxmysql.git resources/[core]/oxmysql"

  - action: "run"
    command: "git clone --branch main https://github.com/qbox-project/qbox_jobs.git resources/[jobs]/qbox_jobs"

  - action: "run"
    command: "git clone --branch main https://github.com/qbox-project/qbox_police.git resources/[jobs]/qbox_police"

  - action: "run"
    command: "git clone --branch main https://github.com/qbox-project/qbox_ems.git resources/[jobs]/qbox_ems"

  - action: "run"
    command: "git clone --branch main https://github.com/qbox-project/qbox_mechanic.git resources/[jobs]/qbox_mechanic"

  - action: "run"
    command: "git clone --branch main https://github.com/qbox-project/qbox_garages.git resources/[vehicles]/qbox_garages"

  - action: "run"
    command: "git clone --branch main https://github.com/qbox-project/qbox_vehicleshop.git resources/[vehicles]/qbox_vehicleshop"

  - action: "run"
    command: "git clone --branch main https://github.com/iLLeniumStudios/illenium-appearance.git resources/[interactions]/illenium-appearance"

  - action: "run"
    command: "git clone --branch main https://github.com/qbox-project/qbox_barbershop.git resources/[interactions]/qbox_barbershop"

  - action: "run"
    command: "git clone --branch main https://github.com/qbox-project/qbox_hud.git resources/[ui]/qbox_hud"

  - action: "run"
    command: "git clone --branch main https://github.com/qbox-project/qbox_store.git resources/[economy]/qbox_store"

  - action: "run"
    command: "git clone --branch main https://github.com/qbox-project/qbox_fishing.git resources/[economy]/qbox_fishing"

  - action: "run"
    command: "git clone --branch main https://github.com/qbox-project/qbox_radio.git resources/[interactions]/qbox_radio"

  - action: "run"
    command: "git clone --branch main https://github.com/qbox-project/qbox_houses.git resources/[properties]/qbox_houses"

  - action: "run"
    command: "git clone --branch main https://github.com/qbox-project/qbox_properties.git resources/[properties]/qbox_properties"

  - action: "run"
    command: "git clone --branch main https://github.com/qbox-project/qbox_adminmenu.git resources/[admin]/qbox_adminmenu"

  - action: "run"
    command: "git clone --branch main https://github.com/qbox-project/qbox_weaponshop.git resources/[interactions]/qbox_weaponshop"

  - action: "run"
    command: "git clone --branch main https://github.com/qbox-project/qbox_drugs.git resources/[illegal]/qbox_drugs"

  - action: "run"
    command: "git clone --branch main https://github.com/qbox-project/qbox_bank.git resources/[economy]/qbox_bank"

  - action: "ensure"
    resource: "[core]/qbox_core"
  - action: "ensure"
    resource: "[core]/ox_lib"
  - action: "ensure"
    resource: "[core]/ox_target"
  - action: "ensure"
    resource: "[core]/ox_inventory"
  - action: "ensure"
    resource: "[core]/oxmysql"
  - action: "ensure"
    resource: "[jobs]/qbox_jobs"
  - action: "ensure"
    resource: "[jobs]/qbox_police"
  - action: "ensure"
    resource: "[jobs]/qbox_ems"
  - action: "ensure"
    resource: "[jobs]/qbox_mechanic"
  - action: "ensure"
    resource: "[vehicles]/qbox_garages"
  - action: "ensure"
    resource: "[vehicles]/qbox_vehicleshop"
  - action: "ensure"
    resource: "[interactions]/illenium-appearance"
  - action: "ensure"
    resource: "[interactions]/qbox_barbershop"
  - action: "ensure"
    resource: "[ui]/qbox_hud"
  - action: "ensure"
    resource: "[economy]/qbox_store"
  - action: "ensure"
    resource: "[economy]/qbox_fishing"
  - action: "ensure"
    resource: "[interactions]/qbox_radio"
  - action: "ensure"
    resource: "[properties]/qbox_houses"
  - action: "ensure"
    resource: "[properties]/qbox_properties"
  - action: "ensure"
    resource: "[admin]/qbox_adminmenu"
  - action: "ensure"
    resource: "[interactions]/qbox_weaponshop"
  - action: "ensure"
    resource: "[illegal]/qbox_drugs"
  - action: "ensure"
    resource: "[economy]/qbox_bank"
