name: "Rascal"
author: "abo derascal"
description: "Server Qbox yang stabil dengan fitur fully roleplay dan Illenium Appearance."
version: 1.1

tasks:
  - action: "exec"
    command: "git clone --depth=1 https://github.com/qbox-project/qbox.git resources/[core]/qbox_core"

  - action: "exec"
    command: "git clone --depth=1 https://github.com/overextended/ox_lib.git resources/[core]/ox_lib"

  - action: "exec"
    command: "git clone --depth=1 https://github.com/overextended/ox_target.git resources/[core]/ox_target"

  - action: "exec"
    command: "git clone --depth=1 https://github.com/overextended/ox_inventory.git resources/[core]/ox_inventory"

  - action: "exec"
    command: "git clone --depth=1 https://github.com/overextended/oxmysql.git resources/[core]/oxmysql"

  - action: "exec"
    command: "git clone --depth=1 https://github.com/qbox-project/qbox_jobs.git resources/[jobs]/qbox_jobs"

  - action: "exec"
    command: "git clone --depth=1 https://github.com/qbox-project/qbox_police.git resources/[jobs]/qbox_police"

  - action: "exec"
    command: "git clone --depth=1 https://github.com/qbox-project/qbox_ems.git resources/[jobs]/qbox_ems"

  - action: "exec"
    command: "git clone --depth=1 https://github.com/qbox-project/qbox_mechanic.git resources/[jobs]/qbox_mechanic"

  - action: "exec"
    command: "git clone --depth=1 https://github.com/qbox-project/qbox_garages.git resources/[vehicles]/qbox_garages"

  - action: "exec"
    command: "git clone --depth=1 https://github.com/qbox-project/qbox_vehicleshop.git resources/[vehicles]/qbox_vehicleshop"

  - action: "exec"
    command: "git clone --depth=1 https://github.com/iLLeniumStudios/illenium-appearance.git resources/[interactions]/illenium-appearance"

  - action: "exec"
    command: "git clone --depth=1 https://github.com/qbox-project/qbox_barbershop.git resources/[interactions]/qbox_barbershop"

  - action: "exec"
    command: "git clone --depth=1 https://github.com/qbox-project/qbox_hud.git resources/[ui]/qbox_hud"

  - action: "exec"
    command: "git clone --depth=1 https://github.com/qbox-project/qbox_store.git resources/[economy]/qbox_store"

  - action: "exec"
    command: "git clone --depth=1 https://github.com/qbox-project/qbox_fishing.git resources/[economy]/qbox_fishing"

  - action: "exec"
    command: "git clone --depth=1 https://github.com/qbox-project/qbox_radio.git resources/[interactions]/qbox_radio"

  - action: "exec"
    command: "git clone --depth=1 https://github.com/qbox-project/qbox_houses.git resources/[properties]/qbox_houses"

  - action: "exec"
    command: "git clone --depth=1 https://github.com/qbox-project/qbox_properties.git resources/[properties]/qbox_properties"

  - action: "exec"
    command: "git clone --depth=1 https://github.com/qbox-project/qbox_adminmenu.git resources/[admin]/qbox_adminmenu"

  - action: "exec"
    command: "git clone --depth=1 https://github.com/qbox-project/qbox_weaponshop.git resources/[interactions]/qbox_weaponshop"

  - action: "exec"
    command: "git clone --depth=1 https://github.com/qbox-project/qbox_drugs.git resources/[illegal]/qbox_drugs"

  - action: "exec"
    command: "git clone --depth=1 https://github
