name: "Rascal"
author: "abo derascal"
description: "Server Qbox yang stabil dengan fitur fully roleplay dan Illenium Appearance."
version: 1.1

tasks:
  - action: "download_github"
    url: "https://github.com/qbox-project/qbox"
    ref: "main"
    dest: "resources/[core]/qbox_core"

  - action: "download_github"
    url: "https://github.com/overextended/ox_lib"
    ref: "main"
    dest: "resources/[core]/ox_lib"

  - action: "download_github"
    url: "https://github.com/overextended/ox_target"
    ref: "main"
    dest: "resources/[core]/ox_target"

  - action: "download_github"
    url: "https://github.com/overextended/ox_inventory"
    ref: "main"
    dest: "resources/[core]/ox_inventory"

  - action: "download_github"
    url: "https://github.com/overextended/oxmysql"
    ref: "main"
    dest: "resources/[core]/oxmysql"

  - action: "download_github"
    url: "https://github.com/qbox-project/qbox_jobs"
    ref: "main"
    dest: "resources/[jobs]/qbox_jobs"

  - action: "download_github"
    url: "https://github.com/qbox-project/qbox_police"
    ref: "main"
    dest: "resources/[jobs]/qbox_police"

  - action: "download_github"
    url: "https://github.com/qbox-project/qbox_ems"
    ref: "main"
    dest: "resources/[jobs]/qbox_ems"

  - action: "download_github"
    url: "https://github.com/qbox-project/qbox_mechanic"
    ref: "main"
    dest: "resources/[jobs]/qbox_mechanic"

  - action: "download_github"
    url: "https://github.com/qbox-project/qbox_garages"
    ref: "main"
    dest: "resources/[vehicles]/qbox_garages"

  - action: "download_github"
    url: "https://github.com/qbox-project/qbox_vehicleshop"
    ref: "main"
    dest: "resources/[vehicles]/qbox_vehicleshop"

  - action: "download_github"
    url: "https://github.com/iLLeniumStudios/illenium-appearance"
    ref: "main"
    dest: "resources/[interactions]/illenium-appearance"

  - action: "download_github"
    url: "https://github.com/qbox-project/qbox_barbershop"
    ref: "main"
    dest: "resources/[interactions]/qbox_barbershop"

  - action: "download_github"
    url: "https://github.com/qbox-project/qbox_hud"
    ref: "main"
    dest: "resources/[ui]/qbox_hud"

  - action: "download_github"
    url: "https://github.com/qbox-project/qbox_store"
    ref: "main"
    dest: "resources/[economy]/qbox_store"

  - action: "download_github"
    url: "https://github.com/qbox-project/qbox_fishing"
    ref: "main"
    dest: "resources/[economy]/qbox_fishing"

  - action: "download_github"
    url: "https://github.com/qbox-project/qbox_radio"
    ref: "main"
    dest: "resources/[interactions]/qbox_radio"

  - action: "download_github"
    url: "https://github.com/qbox-project/qbox_houses"
    ref: "main"
    dest: "resources/[properties]/qbox_houses"

  - action: "download_github"
    url: "https://github.com/qbox-project/qbox_properties"
    ref: "main"
    dest: "resources/[properties]/qbox_properties"

  - action: "download_github"
    url: "https://github.com/qbox-project/qbox_adminmenu"
    ref: "main"
    dest: "resources/[admin]/qbox_adminmenu"

  - action: "download_github"
    url: "https://github.com/qbox-project/qbox_weaponshop"
    ref: "main"
    dest: "resources/[interactions]/qbox_weaponshop"

  - action: "download_github"
    url: "https://github.com/qbox-project/qbox_drugs"
    ref: "main"
    dest: "resources/[illegal]/qbox_drugs"

  - action: "download_github"
    url: "https://github.com/qbox-project/qbox_bank"
    ref: "main"
    dest: "resources/[economy]/qbox_bank"

  - action: "ensure"
    resource: "[core]/qbox_core"
  - action: "ensure"
    resource: "[core]/ox_lib"
  - action: "ensure"
    resource: "[core]/ox_target"
  - action: "ensure"
    resource: "[core]/ox_inventory"
  - action: "ensure"
    resource: "[core]/oxmysql"
  - action: "ensure"
    resource: "[jobs]/qbox_jobs"
  - action: "ensure"
    resource: "[jobs]/qbox_police"
  - action: "ensure"
    resource: "[jobs]/qbox_ems"
  - action: "ensure"
    resource: "[jobs]/qbox_mechanic"
  - action: "ensure"
    resource: "[vehicles]/qbox_garages"
  - action: "ensure"
    resource: "[vehicles]/qbox_vehicleshop"
  - action: "ensure"
    resource: "[interactions]/illenium-appearance"
  - action: "ensure"
    resource: "[interactions]/qbox_barbershop"
  - action: "ensure"
    resource: "[ui]/qbox_hud"
  - action: "ensure"
    resource: "[economy]/qbox_store"
  - action: "ensure"
    resource: "[economy]/qbox_fishing"
  - action: "ensure"
    resource: "[interactions]/qbox_radio"
  - action: "ensure"
    resource: "[properties]/qbox_houses"
  - action: "ensure"
    resource: "[properties]/qbox_properties"
  - action: "ensure"
    resource: "[admin]/qbox_adminmenu"
  - action: "ensure"
    resource: "[interactions]/qbox_weaponshop"
  - action: "ensure"
    resource: "[illegal]/qbox_drugs"
  - action: "ensure"
    resource: "[economy]/qbox_bank"
